baseURL: http://localhost/
title: Hugo Blog Course
# alternate copyright company text
copyright: Camilo Correa
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 10
# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true
# config for related posts

related:
  # pages which are newer than the current page
  includeNewer: true
  # seach terms
  indices:
    - applyFilter: true
      cardinalityThreshold: 0
      name: categories
      pattern: ""
      toLower: true
      type: basic
      weight: 100
    - applyFilter: false
      cardinalityThreshold: 0
      name: date
      pattern: ""
      toLower: false
      type: basic
      weight: 10
    - applyFilter: true
      cardinalityThreshold: 0
      name: tags
      pattern: ""
      toLower: true
      type: basic
      weight: 80
  threshold: 80
  # lowercase search query
  toLower: true

params:
  dateFormat: "02/01/2006"
  widgets:
    - recent-posts
    - related-posts
    - post-categories
    - post-tags
  # control the number of items in widgets
  relatedPosts: 5
  recentPosts: 5
  # postTags: 10
